const ADD_REVIEW = 'ADD_REVIEW';
const ADD_TO_CART = 'ADD_TO_CART';
const LOAD_CART = 'LOAD_CART';
const CHECKOUT = 'CHECKOUT';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const COMPLETE_PAYMENT = 'COMPLETE_PAYMENT';

export default {
  ADD_REVIEW,
  ADD_TO_CART,
  LOAD_CART,
  CHECKOUT,
  REMOVE_FROM_CART,
  COMPLETE_PAYMENT,
};
